// ISO 3166-1 alpha-3 code mapping to Country Name and Flag Emoji
export const ISO3_COUNTRIES = {
  ABW: { name: "Aruba", flag: "🇦🇼" },
  AFG: { name: "Afghanistan", flag: "🇦🇫" },
  AGO: { name: "Angola", flag: "🇦🇴" },
  AIA: { name: "Anguilla", flag: "🇦🇮" },
  ALB: { name: "Albania", flag: "🇦🇱" },
  AND: { name: "Andorra", flag: "🇦🇩" },
  ANT: { name: "Netherlands Antilles", flag: "🇳🇱" },
  ARE: { name: "United Arab Emirates", flag: "🇦🇪" },
  ARG: { name: "Argentina", flag: "🇦🇷" },
  ARM: { name: "Armenia", flag: "🇦🇲" },
  ATG: { name: "Antigua and Barbuda", flag: "🇦🇬" },
  AUS: { name: "Australia", flag: "🇦🇺" },
  AUT: { name: "Austria", flag: "🇦🇹" },
  AZE: { name: "Azerbaijan", flag: "🇦🇿" },
  BDI: { name: "Burundi", flag: "🇧🇮" },
  BEL: { name: "Belgium", flag: "🇧🇪" },
  BEN: { name: "Benin", flag: "🇧🇯" },
  BES: { name: "Bonaire", flag: "🇧🇶" },
  BFA: { name: "Burkina Faso", flag: "🇧🇫" },
  BGD: { name: "Bangladesh", flag: "🇧🇩" },
  BGR: { name: "Bulgaria", flag: "🇧🇬" },
  BHR: { name: "Bahrain", flag: "🇧🇭" },
  BHS: { name: "Bahamas", flag: "🇧🇸" },
  BIH: { name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  BLM: { name: "Saint Barthélemy", flag: "🇧🇱" },
  BLR: { name: "Belarus", flag: "🇧🇾" },
  BLZ: { name: "Belize", flag: "🇧🇿" },
  BMU: { name: "Bermuda", flag: "🇧🇲" },
  BOL: { name: "Bolivia", flag: "🇧🇴" },
  BRA: { name: "Brazil", flag: "🇧🇷" },
  BRB: { name: "Barbados", flag: "🇧🇧" },
  BRN: { name: "Brunei", flag: "🇧🇳" },
  BTN: { name: "Bhutan", flag: "🇧🇹" },
  BWA: { name: "Botswana", flag: "🇧🇼" },
  CAF: { name: "Central African Republic", flag: "🇨🇫" },
  CAN: { name: "Canada", flag: "🇨🇦" },
  CHE: { name: "Switzerland", flag: "🇨🇭" },
  CHL: { name: "Chile", flag: "🇨🇱" },
  CHN: { name: "China", flag: "🇨🇳" },
  CIV: { name: "Côte d'Ivoire", flag: "🇨🇮" },
  CMR: { name: "Cameroon", flag: "🇨🇲" },
  COD: { name: "DR Congo", flag: "🇨🇩" },
  COG: { name: "Congo", flag: "🇨🇬" },
  COL: { name: "Colombia", flag: "🇨🇴" },
  COM: { name: "Comoros", flag: "🇰🇲" },
  CPV: { name: "Cape Verde", flag: "🇨🇻" },
  CRI: { name: "Costa Rica", flag: "🇨🇷" },
  CUB: { name: "Cuba", flag: "🇨🇺" },
  CUW: { name: "Curaçao", flag: "🇨🇼" },
  CYM: { name: "Cayman Islands", flag: "🇰🇾" },
  CYP: { name: "Cyprus", flag: "🇨🇾" },
  CZE: { name: "Czech Republic", flag: "🇨🇿" },
  DEU: { name: "Germany", flag: "🇩🇪" },
  DJI: { name: "Djibouti", flag: "🇩🇯" },
  DMA: { name: "Dominica", flag: "🇩🇲" },
  DNK: { name: "Denmark", flag: "🇩🇰" },
  DOM: { name: "Dominican Republic", flag: "🇩🇴" },
  DZA: { name: "Algeria", flag: "🇩🇿" },
  ECU: { name: "Ecuador", flag: "🇪🇨" },
  EGY: { name: "Egypt", flag: "🇪🇬" },
  ESP: { name: "Spain", flag: "🇪🇸" },
  EST: { name: "Estonia", flag: "🇪🇪" },
  ETH: { name: "Ethiopia", flag: "🇪🇹" },
  FIN: { name: "Finland", flag: "🇫🇮" },
  FJI: { name: "Fiji", flag: "🇫🇯" },
  FRA: { name: "France", flag: "🇫🇷" },
  FRO: { name: "Faroe Islands", flag: "🇫🇴" },
  GAB: { name: "Gabon", flag: "🇬🇦" },
  GBR: { name: "United Kingdom", flag: "🇬🇧" },
  GEO: { name: "Georgia", flag: "🇬🇪" },
  GGY: { name: "Guernsey", flag: "🇬🇬" },
  GHA: { name: "Ghana", flag: "🇬🇭" },
  GIB: { name: "Gibraltar", flag: "🇬🇮" },
  GIN: { name: "Guinea", flag: "🇬🇳" },
  GLP: { name: "Guadeloupe", flag: "🇬🇵" },
  GNB: { name: "Guinea-Bissau", flag: "🇬🇼" },
  GNQ: { name: "Equatorial Guinea", flag: "🇬🇶" },
  GRC: { name: "Greece", flag: "🇬🇷" },
  GRD: { name: "Grenada", flag: "🇬🇩" },
  GRL: { name: "Greenland", flag: "🇬🇱" },
  GTM: { name: "Guatemala", flag: "🇬🇹" },
  GUF: { name: "French Guiana", flag: "🇬🇫" },
  GUY: { name: "Guyana", flag: "🇬🇾" },
  HKG: { name: "Hong Kong", flag: "🇭🇰" },
  HND: { name: "Honduras", flag: "🇭🇳" },
  HRV: { name: "Croatia", flag: "🇭🇷" },
  HTI: { name: "Haiti", flag: "🇭🇹" },
  HUN: { name: "Hungary", flag: "🇭🇺" },
  IDN: { name: "Indonesia", flag: "🇮🇩" },
  IMN: { name: "Isle of Man", flag: "🇮🇲" },
  IND: { name: "India", flag: "🇮🇳" },
  IRL: { name: "Ireland", flag: "🇮🇪" },
  IRQ: { name: "Iraq", flag: "🇮🇶" },
  ISL: { name: "Iceland", flag: "🇮🇸" },
  ISR: { name: "Israel", flag: "🇮🇱" },
  ITA: { name: "Italy", flag: "🇮🇹" },
  JAM: { name: "Jamaica", flag: "🇯🇲" },
  JEY: { name: "Jersey", flag: "🇯🇪" },
  JOR: { name: "Jordan", flag: "🇯🇴" },
  JPN: { name: "Japan", flag: "🇯🇵" },
  KAZ: { name: "Kazakhstan", flag: "🇰🇿" },
  KEN: { name: "Kenya", flag: "🇰🇪" },
  KGZ: { name: "Kyrgyzstan", flag: "🇰🇬" },
  KHM: { name: "Cambodia", flag: "🇰🇭" },
  KNA: { name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  KOR: { name: "South Korea", flag: "🇰🇷" },
  KWT: { name: "Kuwait", flag: "🇰🇼" },
  LAO: { name: "Laos", flag: "🇱🇦" },
  LBN: { name: "Lebanon", flag: "🇱🇧" },
  LBR: { name: "Liberia", flag: "🇱🇷" },
  LCA: { name: "Saint Lucia", flag: "🇱🇨" },
  LIE: { name: "Liechtenstein", flag: "🇱🇮" },
  LKA: { name: "Sri Lanka", flag: "🇱🇰" },
  LSO: { name: "Lesotho", flag: "🇱🇸" },
  LTU: { name: "Lithuania", flag: "🇱🇹" },
  LUX: { name: "Luxembourg", flag: "🇱🇺" },
  LVA: { name: "Latvia", flag: "🇱🇻" },
  MAC: { name: "Macau", flag: "🇲🇴" },
  MAF: { name: "Saint Martin", flag: "🇲🇫" },
  MAR: { name: "Morocco", flag: "🇲🇦" },
  MCO: { name: "Monaco", flag: "🇲🇨" },
  MDA: { name: "Moldova", flag: "🇲🇩" },
  MDG: { name: "Madagascar", flag: "🇲🇬" },
  MEX: { name: "Mexico", flag: "🇲🇽" },
  MKD: { name: "North Macedonia", flag: "🇲🇰" },
  MLI: { name: "Mali", flag: "🇲🇱" },
  MLT: { name: "Malta", flag: "🇲🇹" },
  MNE: { name: "Montenegro", flag: "🇲🇪" },
  MOZ: { name: "Mozambique", flag: "🇲🇿" },
  MRT: { name: "Mauritania", flag: "🇲🇷" },
  MSR: { name: "Montserrat", flag: "🇲🇸" },
  MTQ: { name: "Martinique", flag: "🇲🇶" },
  MUS: { name: "Mauritius", flag: "🇲🇺" },
  MWI: { name: "Malawi", flag: "🇲🇼" },
  MYS: { name: "Malaysia", flag: "🇲🇾" },
  MYT: { name: "Mayotte", flag: "🇾🇹" },
  NAM: { name: "Namibia", flag: "🇳🇦" },
  NGA: { name: "Nigeria", flag: "🇳🇬" },
  NIC: { name: "Nicaragua", flag: "🇳🇮" },
  NLD: { name: "Netherlands", flag: "🇳🇱" },
  NOR: { name: "Norway", flag: "🇳🇴" },
  NPL: { name: "Nepal", flag: "🇳🇵" },
  NRU: { name: "Nauru", flag: "🇳🇷" },
  NZL: { name: "New Zealand", flag: "🇳🇿" },
  OMN: { name: "Oman", flag: "🇴🇲" },
  PAK: { name: "Pakistan", flag: "🇵🇰" },
  PAN: { name: "Panama", flag: "🇵🇦" },
  PER: { name: "Peru", flag: "🇵🇪" },
  PHL: { name: "Philippines", flag: "🇵🇭" },
  POL: { name: "Poland", flag: "🇵🇱" },
  PRI: { name: "Puerto Rico", flag: "🇵🇷" },
  PRT: { name: "Portugal", flag: "🇵🇹" },
  PRY: { name: "Paraguay", flag: "🇵🇾" },
  PYF: { name: "French Polynesia", flag: "🇵🇫" },
  QAT: { name: "Qatar", flag: "🇶🇦" },
  REU: { name: "Réunion", flag: "🇷🇪" },
  ROU: { name: "Romania", flag: "🇷🇴" },
  RUS: { name: "Russia", flag: "🇷🇺" },
  RWA: { name: "Rwanda", flag: "🇷🇼" },
  SAU: { name: "Saudi Arabia", flag: "🇸🇦" },
  SDN: { name: "Sudan", flag: "🇸🇩" },
  SEN: { name: "Senegal", flag: "🇸🇳" },
  SGP: { name: "Singapore", flag: "🇸🇬" },
  SLE: { name: "Sierra Leone", flag: "🇸🇱" },
  SLV: { name: "El Salvador", flag: "🇸🇻" },
  SMR: { name: "San Marino", flag: "🇸🇲" },
  SRB: { name: "Serbia", flag: "🇷🇸" },
  SSD: { name: "South Sudan", flag: "🇸🇸" },
  SUR: { name: "Suriname", flag: "🇸🇷" },
  SVK: { name: "Slovakia", flag: "🇸🇰" },
  SVN: { name: "Slovenia", flag: "🇸🇮" },
  SWE: { name: "Sweden", flag: "🇸🇪" },
  SWZ: { name: "Eswatini", flag: "🇸🇿" },
  SXM: { name: "Sint Maarten", flag: "🇸🇽" },
  SYC: { name: "Seychelles", flag: "🇸🇨" },
  TCA: { name: "Turks and Caicos", flag: "🇹🇨" },
  THA: { name: "Thailand", flag: "🇹🇭" },
  TJK: { name: "Tajikistan", flag: "🇹🇯" },
  TON: { name: "Tonga", flag: "🇹🇴" },
  TTO: { name: "Trinidad and Tobago", flag: "🇹🇹" },
  TUN: { name: "Tunisia", flag: "🇹🇳" },
  TUR: { name: "Turkey", flag: "🇹🇷" },
  TWN: { name: "Taiwan", flag: "🇹🇼" },
  TZA: { name: "Tanzania", flag: "🇹🇿" },
  UGA: { name: "Uganda", flag: "🇺🇬" },
  UKR: { name: "Ukraine", flag: "🇺🇦" },
  URY: { name: "Uruguay", flag: "🇺🇾" },
  USA: { name: "United States", flag: "🇺🇸" },
  UZB: { name: "Uzbekistan", flag: "🇺🇿" },
  VAT: { name: "Vatican City", flag: "🇻🇦" },
  VCT: { name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  VEN: { name: "Venezuela", flag: "🇻🇪" },
  VGB: { name: "British Virgin Islands", flag: "🇻🇬" },
  VIR: { name: "U.S. Virgin Islands", flag: "🇻🇮" },
  VNM: { name: "Vietnam", flag: "🇻🇳" },
  VUT: { name: "Vanuatu", flag: "🇻🇺" },
  WSM: { name: "Samoa", flag: "🇼🇸" },
  XKX: { name: "Kosovo", flag: "🇽🇰" },
  YEM: { name: "Yemen", flag: "🇾🇪" },
  ZAF: { name: "South Africa", flag: "🇿🇦" },
  ZMB: { name: "Zambia", flag: "🇿🇲" },
  ZWE: { name: "Zimbabwe", flag: "🇿🇼" },
};

export function getCountryInfo(iso3Code) {
  if (!iso3Code) return { name: "Unknown", flag: "🌐" };
  const upper = iso3Code.toUpperCase();
  if (ISO3_COUNTRIES[upper]) {
    return ISO3_COUNTRIES[upper];
  }
  return { name: iso3Code, flag: "🌐" };
}
